//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_Items = new HashSet<Bill_Items>();
        }
        [DisplayName("Mã hóa đơn")]
        [Required(ErrorMessage = "Vui lòng nhập mã hóa đơn.")]
        public int id { get; set; }
        [DisplayName("Nhân viên")]
        public string staff_id { get; set; }
        [DisplayName("Khách hàng")]
        public Nullable<int> member_id { get; set; }
        [DisplayName("Mã đặt bàn")]
        public Nullable<int> reservation_id { get; set; }
        [DisplayName("Bàn số")]
        public Nullable<int> table_id { get; set; }
        [DisplayName("Phương thức thanh toán")]
        [Required(ErrorMessage = "Vui lòng chọn phương thức thanh toán.")]
        public string payment_method { get; set; }
        [DisplayName("Ngày thanh toán")]
        public Nullable<System.DateTime> bill_time { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> total_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Items> Bill_Items { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
