//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill_Items
    {
        [DisplayName("Mã chi tiết hóa đơn")]
        [Required(ErrorMessage = "Vui lòng nhập mã chi tiết hóa đơn.")]
        public int id { get; set; }
        [DisplayName("Mã hóa đơn")]
        [Required(ErrorMessage = "Vui lòng nhập mã hóa đơn.")]
        public Nullable<int> bill_id { get; set; }
        [DisplayName("Món")]
        public Nullable<int> item_id { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng.")]
        public Nullable<int> quantity { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
