//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite_Items
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> item_id { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
