//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Favorite_Items
    {
        [DisplayName("Mã yêu thích")]
        [Required(ErrorMessage = "Vui lòng nhập mã yêu thích.")]
        public int id { get; set; }
        [DisplayName("Mã thành viên")]
        [Required(ErrorMessage = "Vui lòng nhập mã thành viên.")]
        public Nullable<int> member_id { get; set; }
        [DisplayName("Món")]
        [Required(ErrorMessage = "Vui lòng nhập mã món.")]
        public Nullable<int> item_id { get; set; }
        
        public virtual Menu Menu { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
