//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Membership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membership()
        {
            this.Bills = new HashSet<Bill>();
            this.Favorite_Items = new HashSet<Favorite_Items>();
        }
        [DisplayName("Mã thành viên")]
        [Required(ErrorMessage = "Vui lòng nhập mã thành viên.")]
        public int id { get; set; }
        [DisplayName("Tên thành viên")]
        [Required(ErrorMessage = "Vui lòng nhập tên thành viên.")]
        public string name { get; set; }
        [DisplayName("Điểm")]
        [Required(ErrorMessage = "Vui lòng nhập điểm.")]
        public Nullable<int> points { get; set; }
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập mã tài khoản.")]
        public Nullable<int> account_id { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Items> Favorite_Items { get; set; }
    }
}
