//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Bill_Items = new HashSet<Bill_Items>();
            this.Favorite_Items = new HashSet<Favorite_Items>();
        }
        [DisplayName("Mã món")]
        [Required(ErrorMessage = "Vui lòng nhập mã món.")]
        public int id { get; set; }
        [DisplayName("Ảnh ")]
        [Required(ErrorMessage = "Vui lòng nhập ảnh.")]
        public string img { get; set; }
        [DisplayName("Tên món")]
        [Required(ErrorMessage = "Vui lòng nhập tên món.")]
        public string name { get; set; }
        [DisplayName("Loại thực đơn")]
        [Required(ErrorMessage = "Vui lòng nhập mã loại thực đơn.")]
        public string category_id { get; set; }
        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Vui lòng nhập đơn giá.")]
        public Nullable<decimal> price { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả.")]
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Items> Bill_Items { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Items> Favorite_Items { get; set; }
    }
}
