//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Bills = new HashSet<Bill>();
        }
        [DisplayName("Mã đặt bàn")]
        [Required(ErrorMessage = "Vui lòng nhập mã đặt bàn.")]
        public int reservation_id { get; set; }
        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage = "Vui lòng nhập tên khách hàng.")]
        public string customer_name { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại.")]
        public string phone_number { get; set; }
        [DisplayName("Bàn")]
        [Required(ErrorMessage = "Vui lòng nhập mã bàn.")]
        public Nullable<int> table_id { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng.")]
        public Nullable<int> quantity { get; set; }
        [DisplayName("Thời gian đặt bàn")]
        [Required(ErrorMessage = "Vui lòng nhập thời gian đặt.")]
        public Nullable<System.TimeSpan> reservation_time { get; set; }
        [DisplayName("Ngày đặt bàn")]
        [Required(ErrorMessage = "Vui lòng nhập ngày đặt bàn.")]
        public Nullable<System.DateTime> reservation_date { get; set; }
        [DisplayName("Ghi chú")]
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Table_Res Table_Res { get; set; }
    }
}
