//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int reservation_id { get; set; }
        public string customer_name { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> table_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.TimeSpan> reservation_time { get; set; }
        public Nullable<System.DateTime> reservation_date { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Table_Res Table_Res { get; set; }
    }
}
