//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Restaurant_Web_DataEntities : DbContext
    {
        public Restaurant_Web_DataEntities()
            : base("name=Restaurant_Web_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bill_Items> Bill_Items { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Card_payments> Card_payments { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Deal> Deals { get; set; }
        public virtual DbSet<Favorite_Items> Favorite_Items { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Table_Res> Table_Res { get; set; }
    }
}
